// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kk_schedule/Base.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBRegisterJob struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
	// ServiceName + FuncName must be unique
	ServiceName   string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	FuncName      string `protobuf:"bytes,3,opt,name=FuncName,proto3" json:"FuncName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRegisterJob) Reset() {
	*x = PBRegisterJob{}
	mi := &file_kk_schedule_Base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRegisterJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRegisterJob) ProtoMessage() {}

func (x *PBRegisterJob) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_Base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRegisterJob.ProtoReflect.Descriptor instead.
func (*PBRegisterJob) Descriptor() ([]byte, []int) {
	return file_kk_schedule_Base_proto_rawDescGZIP(), []int{0}
}

func (x *PBRegisterJob) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PBRegisterJob) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PBRegisterJob) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

type PBRegisterService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Eg 127.0.0.1:8081
	Target string `protobuf:"bytes,1,opt,name=Target,proto3" json:"Target,omitempty"`
	// ServiceName must be unique
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	// Authentication token for the service
	AuthToken     string `protobuf:"bytes,3,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRegisterService) Reset() {
	*x = PBRegisterService{}
	mi := &file_kk_schedule_Base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRegisterService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRegisterService) ProtoMessage() {}

func (x *PBRegisterService) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_Base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRegisterService.ProtoReflect.Descriptor instead.
func (*PBRegisterService) Descriptor() ([]byte, []int) {
	return file_kk_schedule_Base_proto_rawDescGZIP(), []int{1}
}

func (x *PBRegisterService) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PBRegisterService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PBRegisterService) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

var File_kk_schedule_Base_proto protoreflect.FileDescriptor

const file_kk_schedule_Base_proto_rawDesc = "" +
	"\n" +
	"\x16kk_schedule/Base.proto\x12\vkk_schedule\"o\n" +
	"\rPBRegisterJob\x12 \n" +
	"\vDescription\x18\x01 \x01(\tR\vDescription\x12 \n" +
	"\vServiceName\x18\x02 \x01(\tR\vServiceName\x12\x1a\n" +
	"\bFuncName\x18\x03 \x01(\tR\bFuncName\"k\n" +
	"\x11PBRegisterService\x12\x16\n" +
	"\x06Target\x18\x01 \x01(\tR\x06Target\x12 \n" +
	"\vServiceName\x18\x02 \x01(\tR\vServiceName\x12\x1c\n" +
	"\tAuthToken\x18\x03 \x01(\tR\tAuthTokenB\x0eZ\f/kk_scheduleb\x06proto3"

var (
	file_kk_schedule_Base_proto_rawDescOnce sync.Once
	file_kk_schedule_Base_proto_rawDescData []byte
)

func file_kk_schedule_Base_proto_rawDescGZIP() []byte {
	file_kk_schedule_Base_proto_rawDescOnce.Do(func() {
		file_kk_schedule_Base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_schedule_Base_proto_rawDesc), len(file_kk_schedule_Base_proto_rawDesc)))
	})
	return file_kk_schedule_Base_proto_rawDescData
}

var file_kk_schedule_Base_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kk_schedule_Base_proto_goTypes = []any{
	(*PBRegisterJob)(nil),     // 0: kk_schedule.PBRegisterJob
	(*PBRegisterService)(nil), // 1: kk_schedule.PBRegisterService
}
var file_kk_schedule_Base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_schedule_Base_proto_init() }
func file_kk_schedule_Base_proto_init() {
	if File_kk_schedule_Base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_Base_proto_rawDesc), len(file_kk_schedule_Base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_Base_proto_goTypes,
		DependencyIndexes: file_kk_schedule_Base_proto_depIdxs,
		MessageInfos:      file_kk_schedule_Base_proto_msgTypes,
	}.Build()
	File_kk_schedule_Base_proto = out.File
	file_kk_schedule_Base_proto_goTypes = nil
	file_kk_schedule_Base_proto_depIdxs = nil
}
