// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kk_schedule/Job.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryID       int32                  `protobuf:"varint,1,opt,name=EntryID,proto3" json:"EntryID,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	Next          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Next,proto3" json:"Next,omitempty"`
	Prev          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=Prev,proto3" json:"Prev,omitempty"`
	Spec          string                 `protobuf:"bytes,5,opt,name=Spec,proto3" json:"Spec,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	FuncName      string                 `protobuf:"bytes,7,opt,name=FuncName,proto3" json:"FuncName,omitempty"`
	ServiceName   string                 `protobuf:"bytes,8,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBJob) Reset() {
	*x = PBJob{}
	mi := &file_kk_schedule_Job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBJob) ProtoMessage() {}

func (x *PBJob) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_Job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBJob.ProtoReflect.Descriptor instead.
func (*PBJob) Descriptor() ([]byte, []int) {
	return file_kk_schedule_Job_proto_rawDescGZIP(), []int{0}
}

func (x *PBJob) GetEntryID() int32 {
	if x != nil {
		return x.EntryID
	}
	return 0
}

func (x *PBJob) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PBJob) GetNext() *timestamppb.Timestamp {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *PBJob) GetPrev() *timestamppb.Timestamp {
	if x != nil {
		return x.Prev
	}
	return nil
}

func (x *PBJob) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *PBJob) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PBJob) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *PBJob) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_kk_schedule_Job_proto protoreflect.FileDescriptor

const file_kk_schedule_Job_proto_rawDesc = "" +
	"\n" +
	"\x15kk_schedule/Job.proto\x12\vkk_schedule\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\x05PBJob\x12\x18\n" +
	"\aEntryID\x18\x01 \x01(\x05R\aEntryID\x12\x18\n" +
	"\aEnabled\x18\x02 \x01(\bR\aEnabled\x12.\n" +
	"\x04Next\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04Next\x12.\n" +
	"\x04Prev\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04Prev\x12\x12\n" +
	"\x04Spec\x18\x05 \x01(\tR\x04Spec\x12 \n" +
	"\vDescription\x18\x06 \x01(\tR\vDescription\x12\x1a\n" +
	"\bFuncName\x18\a \x01(\tR\bFuncName\x12 \n" +
	"\vServiceName\x18\b \x01(\tR\vServiceNameB\x0eZ\f/kk_scheduleb\x06proto3"

var (
	file_kk_schedule_Job_proto_rawDescOnce sync.Once
	file_kk_schedule_Job_proto_rawDescData []byte
)

func file_kk_schedule_Job_proto_rawDescGZIP() []byte {
	file_kk_schedule_Job_proto_rawDescOnce.Do(func() {
		file_kk_schedule_Job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_schedule_Job_proto_rawDesc), len(file_kk_schedule_Job_proto_rawDesc)))
	})
	return file_kk_schedule_Job_proto_rawDescData
}

var file_kk_schedule_Job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kk_schedule_Job_proto_goTypes = []any{
	(*PBJob)(nil),                 // 0: kk_schedule.PBJob
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_kk_schedule_Job_proto_depIdxs = []int32{
	1, // 0: kk_schedule.PBJob.Next:type_name -> google.protobuf.Timestamp
	1, // 1: kk_schedule.PBJob.Prev:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kk_schedule_Job_proto_init() }
func file_kk_schedule_Job_proto_init() {
	if File_kk_schedule_Job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_Job_proto_rawDesc), len(file_kk_schedule_Job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_Job_proto_goTypes,
		DependencyIndexes: file_kk_schedule_Job_proto_depIdxs,
		MessageInfos:      file_kk_schedule_Job_proto_msgTypes,
	}.Build()
	File_kk_schedule_Job_proto = out.File
	file_kk_schedule_Job_proto_goTypes = nil
	file_kk_schedule_Job_proto_depIdxs = nil
}
