// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kk_schedule/JobDelete.proto

package kk_schedule

import (
	_ "gitee.com/cruvie/kk_go_kit/kk_protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDelete) Reset() {
	*x = JobDelete{}
	mi := &file_kk_schedule_JobDelete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDelete) ProtoMessage() {}

func (x *JobDelete) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobDelete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDelete.ProtoReflect.Descriptor instead.
func (*JobDelete) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobDelete_proto_rawDescGZIP(), []int{0}
}

type JobDelete_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	FuncName      string                 `protobuf:"bytes,2,opt,name=funcName,proto3" json:"funcName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDelete_Input) Reset() {
	*x = JobDelete_Input{}
	mi := &file_kk_schedule_JobDelete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDelete_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDelete_Input) ProtoMessage() {}

func (x *JobDelete_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobDelete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDelete_Input.ProtoReflect.Descriptor instead.
func (*JobDelete_Input) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobDelete_proto_rawDescGZIP(), []int{0, 0}
}

func (x *JobDelete_Input) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *JobDelete_Input) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

type JobDelete_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDelete_Output) Reset() {
	*x = JobDelete_Output{}
	mi := &file_kk_schedule_JobDelete_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDelete_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDelete_Output) ProtoMessage() {}

func (x *JobDelete_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobDelete_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDelete_Output.ProtoReflect.Descriptor instead.
func (*JobDelete_Output) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobDelete_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_schedule_JobDelete_proto protoreflect.FileDescriptor

const file_kk_schedule_JobDelete_proto_rawDesc = "" +
	"\n" +
	"\x1bkk_schedule/JobDelete.proto\x12\vkk_schedule\x1a\x15kk_schedule/Job.proto\x1a@vendor/gitee.com/cruvie/kk_go_kit/kk_protobuf/extend_field.proto\"j\n" +
	"\tJobDelete\x1aS\n" +
	"\x05Input\x12'\n" +
	"\vserviceName\x18\x01 \x01(\tB\x05\x8a\xa6\x1d\x01\x01R\vserviceName\x12!\n" +
	"\bfuncName\x18\x02 \x01(\tB\x05\x8a\xa6\x1d\x01\x01R\bfuncName\x1a\b\n" +
	"\x06OutputB\x0eZ\f/kk_scheduleb\x06proto3"

var (
	file_kk_schedule_JobDelete_proto_rawDescOnce sync.Once
	file_kk_schedule_JobDelete_proto_rawDescData []byte
)

func file_kk_schedule_JobDelete_proto_rawDescGZIP() []byte {
	file_kk_schedule_JobDelete_proto_rawDescOnce.Do(func() {
		file_kk_schedule_JobDelete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_schedule_JobDelete_proto_rawDesc), len(file_kk_schedule_JobDelete_proto_rawDesc)))
	})
	return file_kk_schedule_JobDelete_proto_rawDescData
}

var file_kk_schedule_JobDelete_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_JobDelete_proto_goTypes = []any{
	(*JobDelete)(nil),        // 0: kk_schedule.JobDelete
	(*JobDelete_Input)(nil),  // 1: kk_schedule.JobDelete.Input
	(*JobDelete_Output)(nil), // 2: kk_schedule.JobDelete.Output
}
var file_kk_schedule_JobDelete_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_schedule_JobDelete_proto_init() }
func file_kk_schedule_JobDelete_proto_init() {
	if File_kk_schedule_JobDelete_proto != nil {
		return
	}
	file_kk_schedule_Job_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_JobDelete_proto_rawDesc), len(file_kk_schedule_JobDelete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_JobDelete_proto_goTypes,
		DependencyIndexes: file_kk_schedule_JobDelete_proto_depIdxs,
		MessageInfos:      file_kk_schedule_JobDelete_proto_msgTypes,
	}.Build()
	File_kk_schedule_JobDelete_proto = out.File
	file_kk_schedule_JobDelete_proto_goTypes = nil
	file_kk_schedule_JobDelete_proto_depIdxs = nil
}
