// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kk_schedule/JobGet.proto

package kk_schedule

import (
	_ "gitee.com/cruvie/kk_go_kit/kk_protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGet) Reset() {
	*x = JobGet{}
	mi := &file_kk_schedule_JobGet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGet) ProtoMessage() {}

func (x *JobGet) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobGet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGet.ProtoReflect.Descriptor instead.
func (*JobGet) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobGet_proto_rawDescGZIP(), []int{0}
}

type JobGet_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	FuncName      string                 `protobuf:"bytes,2,opt,name=funcName,proto3" json:"funcName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGet_Input) Reset() {
	*x = JobGet_Input{}
	mi := &file_kk_schedule_JobGet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGet_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGet_Input) ProtoMessage() {}

func (x *JobGet_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobGet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGet_Input.ProtoReflect.Descriptor instead.
func (*JobGet_Input) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobGet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *JobGet_Input) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *JobGet_Input) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

type JobGet_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *PBJob                 `protobuf:"bytes,1,opt,name=Job,proto3" json:"Job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGet_Output) Reset() {
	*x = JobGet_Output{}
	mi := &file_kk_schedule_JobGet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGet_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGet_Output) ProtoMessage() {}

func (x *JobGet_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobGet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGet_Output.ProtoReflect.Descriptor instead.
func (*JobGet_Output) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobGet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *JobGet_Output) GetJob() *PBJob {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_kk_schedule_JobGet_proto protoreflect.FileDescriptor

const file_kk_schedule_JobGet_proto_rawDesc = "" +
	"\n" +
	"\x18kk_schedule/JobGet.proto\x12\vkk_schedule\x1a\x15kk_schedule/Job.proto\x1a@vendor/gitee.com/cruvie/kk_go_kit/kk_protobuf/extend_field.proto\"\x8d\x01\n" +
	"\x06JobGet\x1aS\n" +
	"\x05Input\x12'\n" +
	"\vserviceName\x18\x01 \x01(\tB\x05\x8a\xa6\x1d\x01\x01R\vserviceName\x12!\n" +
	"\bfuncName\x18\x02 \x01(\tB\x05\x8a\xa6\x1d\x01\x01R\bfuncName\x1a.\n" +
	"\x06Output\x12$\n" +
	"\x03Job\x18\x01 \x01(\v2\x12.kk_schedule.PBJobR\x03JobB\x0eZ\f/kk_scheduleb\x06proto3"

var (
	file_kk_schedule_JobGet_proto_rawDescOnce sync.Once
	file_kk_schedule_JobGet_proto_rawDescData []byte
)

func file_kk_schedule_JobGet_proto_rawDescGZIP() []byte {
	file_kk_schedule_JobGet_proto_rawDescOnce.Do(func() {
		file_kk_schedule_JobGet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_schedule_JobGet_proto_rawDesc), len(file_kk_schedule_JobGet_proto_rawDesc)))
	})
	return file_kk_schedule_JobGet_proto_rawDescData
}

var file_kk_schedule_JobGet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_JobGet_proto_goTypes = []any{
	(*JobGet)(nil),        // 0: kk_schedule.JobGet
	(*JobGet_Input)(nil),  // 1: kk_schedule.JobGet.Input
	(*JobGet_Output)(nil), // 2: kk_schedule.JobGet.Output
	(*PBJob)(nil),         // 3: kk_schedule.PBJob
}
var file_kk_schedule_JobGet_proto_depIdxs = []int32{
	3, // 0: kk_schedule.JobGet.Output.Job:type_name -> kk_schedule.PBJob
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_schedule_JobGet_proto_init() }
func file_kk_schedule_JobGet_proto_init() {
	if File_kk_schedule_JobGet_proto != nil {
		return
	}
	file_kk_schedule_Job_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_JobGet_proto_rawDesc), len(file_kk_schedule_JobGet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_JobGet_proto_goTypes,
		DependencyIndexes: file_kk_schedule_JobGet_proto_depIdxs,
		MessageInfos:      file_kk_schedule_JobGet_proto_msgTypes,
	}.Build()
	File_kk_schedule_JobGet_proto = out.File
	file_kk_schedule_JobGet_proto_goTypes = nil
	file_kk_schedule_JobGet_proto_depIdxs = nil
}
