// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kk_schedule/JobPut.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobPut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobPut) Reset() {
	*x = JobPut{}
	mi := &file_kk_schedule_JobPut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPut) ProtoMessage() {}

func (x *JobPut) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobPut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPut.ProtoReflect.Descriptor instead.
func (*JobPut) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobPut_proto_rawDescGZIP(), []int{0}
}

type JobPut_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *PBRegisterJob         `protobuf:"bytes,1,opt,name=Job,proto3" json:"Job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobPut_Input) Reset() {
	*x = JobPut_Input{}
	mi := &file_kk_schedule_JobPut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPut_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPut_Input) ProtoMessage() {}

func (x *JobPut_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobPut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPut_Input.ProtoReflect.Descriptor instead.
func (*JobPut_Input) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobPut_proto_rawDescGZIP(), []int{0, 0}
}

func (x *JobPut_Input) GetJob() *PBRegisterJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type JobPut_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobPut_Output) Reset() {
	*x = JobPut_Output{}
	mi := &file_kk_schedule_JobPut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPut_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPut_Output) ProtoMessage() {}

func (x *JobPut_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_JobPut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPut_Output.ProtoReflect.Descriptor instead.
func (*JobPut_Output) Descriptor() ([]byte, []int) {
	return file_kk_schedule_JobPut_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_schedule_JobPut_proto protoreflect.FileDescriptor

const file_kk_schedule_JobPut_proto_rawDesc = "" +
	"\n" +
	"\x18kk_schedule/JobPut.proto\x12\vkk_schedule\x1a\x15kk_schedule/Job.proto\x1a\x16kk_schedule/Base.proto\"I\n" +
	"\x06JobPut\x1a5\n" +
	"\x05Input\x12,\n" +
	"\x03Job\x18\x01 \x01(\v2\x1a.kk_schedule.PBRegisterJobR\x03Job\x1a\b\n" +
	"\x06OutputB\x0eZ\f/kk_scheduleb\x06proto3"

var (
	file_kk_schedule_JobPut_proto_rawDescOnce sync.Once
	file_kk_schedule_JobPut_proto_rawDescData []byte
)

func file_kk_schedule_JobPut_proto_rawDescGZIP() []byte {
	file_kk_schedule_JobPut_proto_rawDescOnce.Do(func() {
		file_kk_schedule_JobPut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_schedule_JobPut_proto_rawDesc), len(file_kk_schedule_JobPut_proto_rawDesc)))
	})
	return file_kk_schedule_JobPut_proto_rawDescData
}

var file_kk_schedule_JobPut_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_JobPut_proto_goTypes = []any{
	(*JobPut)(nil),        // 0: kk_schedule.JobPut
	(*JobPut_Input)(nil),  // 1: kk_schedule.JobPut.Input
	(*JobPut_Output)(nil), // 2: kk_schedule.JobPut.Output
	(*PBRegisterJob)(nil), // 3: kk_schedule.PBRegisterJob
}
var file_kk_schedule_JobPut_proto_depIdxs = []int32{
	3, // 0: kk_schedule.JobPut.Input.Job:type_name -> kk_schedule.PBRegisterJob
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_schedule_JobPut_proto_init() }
func file_kk_schedule_JobPut_proto_init() {
	if File_kk_schedule_JobPut_proto != nil {
		return
	}
	file_kk_schedule_Job_proto_init()
	file_kk_schedule_Base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_JobPut_proto_rawDesc), len(file_kk_schedule_JobPut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_JobPut_proto_goTypes,
		DependencyIndexes: file_kk_schedule_JobPut_proto_depIdxs,
		MessageInfos:      file_kk_schedule_JobPut_proto_msgTypes,
	}.Build()
	File_kk_schedule_JobPut_proto = out.File
	file_kk_schedule_JobPut_proto_goTypes = nil
	file_kk_schedule_JobPut_proto_depIdxs = nil
}
