// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kk_schedule/ServiceDelete.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDelete) Reset() {
	*x = ServiceDelete{}
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete) ProtoMessage() {}

func (x *ServiceDelete) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDelete.ProtoReflect.Descriptor instead.
func (*ServiceDelete) Descriptor() ([]byte, []int) {
	return file_kk_schedule_ServiceDelete_proto_rawDescGZIP(), []int{0}
}

type ServiceDelete_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDelete_Input) Reset() {
	*x = ServiceDelete_Input{}
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete_Input) ProtoMessage() {}

func (x *ServiceDelete_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDelete_Input.ProtoReflect.Descriptor instead.
func (*ServiceDelete_Input) Descriptor() ([]byte, []int) {
	return file_kk_schedule_ServiceDelete_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceDelete_Input) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceDelete_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDelete_Output) Reset() {
	*x = ServiceDelete_Output{}
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDelete_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDelete_Output) ProtoMessage() {}

func (x *ServiceDelete_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceDelete_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDelete_Output.ProtoReflect.Descriptor instead.
func (*ServiceDelete_Output) Descriptor() ([]byte, []int) {
	return file_kk_schedule_ServiceDelete_proto_rawDescGZIP(), []int{0, 1}
}

var File_kk_schedule_ServiceDelete_proto protoreflect.FileDescriptor

const file_kk_schedule_ServiceDelete_proto_rawDesc = "" +
	"\n" +
	"\x1fkk_schedule/ServiceDelete.proto\x12\vkk_schedule\"D\n" +
	"\rServiceDelete\x1a)\n" +
	"\x05Input\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x1a\b\n" +
	"\x06OutputB\x0eZ\f/kk_scheduleb\x06proto3"

var (
	file_kk_schedule_ServiceDelete_proto_rawDescOnce sync.Once
	file_kk_schedule_ServiceDelete_proto_rawDescData []byte
)

func file_kk_schedule_ServiceDelete_proto_rawDescGZIP() []byte {
	file_kk_schedule_ServiceDelete_proto_rawDescOnce.Do(func() {
		file_kk_schedule_ServiceDelete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_schedule_ServiceDelete_proto_rawDesc), len(file_kk_schedule_ServiceDelete_proto_rawDesc)))
	})
	return file_kk_schedule_ServiceDelete_proto_rawDescData
}

var file_kk_schedule_ServiceDelete_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_ServiceDelete_proto_goTypes = []any{
	(*ServiceDelete)(nil),        // 0: kk_schedule.ServiceDelete
	(*ServiceDelete_Input)(nil),  // 1: kk_schedule.ServiceDelete.Input
	(*ServiceDelete_Output)(nil), // 2: kk_schedule.ServiceDelete.Output
}
var file_kk_schedule_ServiceDelete_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kk_schedule_ServiceDelete_proto_init() }
func file_kk_schedule_ServiceDelete_proto_init() {
	if File_kk_schedule_ServiceDelete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_ServiceDelete_proto_rawDesc), len(file_kk_schedule_ServiceDelete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_ServiceDelete_proto_goTypes,
		DependencyIndexes: file_kk_schedule_ServiceDelete_proto_depIdxs,
		MessageInfos:      file_kk_schedule_ServiceDelete_proto_msgTypes,
	}.Build()
	File_kk_schedule_ServiceDelete_proto = out.File
	file_kk_schedule_ServiceDelete_proto_goTypes = nil
	file_kk_schedule_ServiceDelete_proto_depIdxs = nil
}
