// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kk_schedule/ServiceList.proto

package kk_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_kk_schedule_ServiceList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_kk_schedule_ServiceList_proto_rawDescGZIP(), []int{0}
}

type ServiceList_Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList_Input) Reset() {
	*x = ServiceList_Input{}
	mi := &file_kk_schedule_ServiceList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList_Input) ProtoMessage() {}

func (x *ServiceList_Input) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList_Input.ProtoReflect.Descriptor instead.
func (*ServiceList_Input) Descriptor() ([]byte, []int) {
	return file_kk_schedule_ServiceList_proto_rawDescGZIP(), []int{0, 0}
}

type ServiceList_Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceList   []*PBRegisterService   `protobuf:"bytes,1,rep,name=ServiceList,proto3" json:"ServiceList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList_Output) Reset() {
	*x = ServiceList_Output{}
	mi := &file_kk_schedule_ServiceList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList_Output) ProtoMessage() {}

func (x *ServiceList_Output) ProtoReflect() protoreflect.Message {
	mi := &file_kk_schedule_ServiceList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList_Output.ProtoReflect.Descriptor instead.
func (*ServiceList_Output) Descriptor() ([]byte, []int) {
	return file_kk_schedule_ServiceList_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServiceList_Output) GetServiceList() []*PBRegisterService {
	if x != nil {
		return x.ServiceList
	}
	return nil
}

var File_kk_schedule_ServiceList_proto protoreflect.FileDescriptor

const file_kk_schedule_ServiceList_proto_rawDesc = "" +
	"\n" +
	"\x1dkk_schedule/ServiceList.proto\x12\vkk_schedule\x1a\x16kk_schedule/Base.proto\"b\n" +
	"\vServiceList\x1a\a\n" +
	"\x05Input\x1aJ\n" +
	"\x06Output\x12@\n" +
	"\vServiceList\x18\x01 \x03(\v2\x1e.kk_schedule.PBRegisterServiceR\vServiceListB\x0eZ\f/kk_scheduleb\x06proto3"

var (
	file_kk_schedule_ServiceList_proto_rawDescOnce sync.Once
	file_kk_schedule_ServiceList_proto_rawDescData []byte
)

func file_kk_schedule_ServiceList_proto_rawDescGZIP() []byte {
	file_kk_schedule_ServiceList_proto_rawDescOnce.Do(func() {
		file_kk_schedule_ServiceList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kk_schedule_ServiceList_proto_rawDesc), len(file_kk_schedule_ServiceList_proto_rawDesc)))
	})
	return file_kk_schedule_ServiceList_proto_rawDescData
}

var file_kk_schedule_ServiceList_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kk_schedule_ServiceList_proto_goTypes = []any{
	(*ServiceList)(nil),        // 0: kk_schedule.ServiceList
	(*ServiceList_Input)(nil),  // 1: kk_schedule.ServiceList.Input
	(*ServiceList_Output)(nil), // 2: kk_schedule.ServiceList.Output
	(*PBRegisterService)(nil),  // 3: kk_schedule.PBRegisterService
}
var file_kk_schedule_ServiceList_proto_depIdxs = []int32{
	3, // 0: kk_schedule.ServiceList.Output.ServiceList:type_name -> kk_schedule.PBRegisterService
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kk_schedule_ServiceList_proto_init() }
func file_kk_schedule_ServiceList_proto_init() {
	if File_kk_schedule_ServiceList_proto != nil {
		return
	}
	file_kk_schedule_Base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kk_schedule_ServiceList_proto_rawDesc), len(file_kk_schedule_ServiceList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kk_schedule_ServiceList_proto_goTypes,
		DependencyIndexes: file_kk_schedule_ServiceList_proto_depIdxs,
		MessageInfos:      file_kk_schedule_ServiceList_proto_msgTypes,
	}.Build()
	File_kk_schedule_ServiceList_proto = out.File
	file_kk_schedule_ServiceList_proto_goTypes = nil
	file_kk_schedule_ServiceList_proto_depIdxs = nil
}
